import {Injectable} from '@angular/core';
import {HttpClient} from "@angular/common/http";
import {AppSettings} from "../app.settings";

@Injectable({
  providedIn: 'root'
})
export class AuthService {

  private _accessToken; // variable to store the access token

  constructor(protected http: HttpClient) {
  }

  as3rdPartyApp(code) {
    // open `AppSettings.AUTH_3RDP_AUTHORIZATION_FULL_URL` first
    return this.http.post(AppSettings.AUTH_3RDP_TOKEN_URL, {
      grant_type: "authorization_code",
      client_id: AppSettings.AS3RDP_CLIENT_ID, // as generated by `php artisan passport:client --client`
      client_secret: AppSettings.AS3RDP_CLIENT_SECRET, // as generated by `php artisan passport:client --client`
      redirect_uri: AppSettings.AS3RDP_CLIENT_REDIRECT_URI, // exactly as in the DB!
      code: code,
    })
      .subscribe(response => {
        // todo: store token
        console.log(response);
      });
  }

  login(username, password) {
    return this.http.post(AppSettings.AUTH_TOKEN_URL, {
      grant_type: "password",
      client_id: AppSettings.CLIENT_ID, // as generated by `php artisan passport:client --client`
      client_secret: AppSettings.CLIENT_SECRET, // as generated by `php artisan passport:client --client`
      username: username,
      password: password,
      scope: "*"
    })
  }

  get accessToken() {
    return this._accessToken;
  }

  set accessToken(accessToken) {
    this._accessToken = accessToken;  // save the access_token
  }
}
